#pragma once

namespace fm
{
    enum MouseButton
    {
        MOUSE_BUTTON_LEFT,
        MOUSE_BUTTON_RIGHT,
        MOUSE_BUTTON_MIDDLE,
        MOUSE_BUTTON_MAX
    };

    enum KeyboardKey
    {
        KEYBOARD_KEY_BACKSPACE = 0x08,
        KEYBOARD_KEY_ENTER = 0x0D,
        KEYBOARD_KEY_TAB = 0x09,
        KEYBOARD_KEY_SHIFT = 0x10,
        KEYBOARD_KEY_CONTROL = 0x11,

        KEYBOARD_KEY_PAUSE = 0x13,
        KEYBOARD_KEY_CAPITAL = 0x14,

        KEYBOARD_KEY_ESCAPE = 0x1B,

        KEYBOARD_KEY_CONVERT = 0x1C,
        KEYBOARD_KEY_NONCONVERT = 0x1D,
        KEYBOARD_KEY_ACCEPT = 0x1E,
        KEYBOARD_KEY_MODECHANGE = 0x1F,

        KEYBOARD_KEY_SPACE = 0x20,
        KEYBOARD_KEY_PAGEUP = 0x21,
        KEYBOARD_KEY_PAGEDOWN = 0x22,
        KEYBOARD_KEY_END = 0x23,
        KEYBOARD_KEY_HOME = 0x24,
        KEYBOARD_KEY_LEFT = 0x25,
        KEYBOARD_KEY_UP = 0x26,
        KEYBOARD_KEY_RIGHT = 0x27,
        KEYBOARD_KEY_DOWN = 0x28,
        KEYBOARD_KEY_SELECT = 0x29,
        KEYBOARD_KEY_PRINT = 0x2A,
        KEYBOARD_KEY_EXECUTE = 0x2B,
        KEYBOARD_KEY_PRINTSCREEN = 0x2C,
        KEYBOARD_KEY_INSERT = 0x2D,
        KEYBOARD_KEY_DELETE = 0x2E,
        KEYBOARD_KEY_HELP = 0x2F,

        KEYBOARD_KEY_0 = 0x30,
        KEYBOARD_KEY_1 = 0x31,
        KEYBOARD_KEY_2 = 0x32,
        KEYBOARD_KEY_3 = 0x33,
        KEYBOARD_KEY_4 = 0x34,
        KEYBOARD_KEY_5 = 0x35,
        KEYBOARD_KEY_6 = 0x36,
        KEYBOARD_KEY_7 = 0x37,
        KEYBOARD_KEY_8 = 0x38,
        KEYBOARD_KEY_9 = 0x39,

        KEYBOARD_KEY_A = 0x41,
        KEYBOARD_KEY_B = 0x42,
        KEYBOARD_KEY_C = 0x43,
        KEYBOARD_KEY_D = 0x44,
        KEYBOARD_KEY_E = 0x45,
        KEYBOARD_KEY_F = 0x46,
        KEYBOARD_KEY_G = 0x47,
        KEYBOARD_KEY_H = 0x48,
        KEYBOARD_KEY_I = 0x49,
        KEYBOARD_KEY_J = 0x4A,
        KEYBOARD_KEY_K = 0x4B,
        KEYBOARD_KEY_L = 0x4C,
        KEYBOARD_KEY_M = 0x4D,
        KEYBOARD_KEY_N = 0x4E,
        KEYBOARD_KEY_O = 0x4F,
        KEYBOARD_KEY_P = 0x50,
        KEYBOARD_KEY_Q = 0x51,
        KEYBOARD_KEY_R = 0x52,
        KEYBOARD_KEY_S = 0x53,
        KEYBOARD_KEY_T = 0x54,
        KEYBOARD_KEY_U = 0x55,
        KEYBOARD_KEY_V = 0x56,
        KEYBOARD_KEY_W = 0x57,
        KEYBOARD_KEY_X = 0x58,
        KEYBOARD_KEY_Y = 0x59,
        KEYBOARD_KEY_Z = 0x5A,

        KEYBOARD_KEY_LSUPER = 0x5B,
        KEYBOARD_KEY_RSUPER = 0x5C,
        KEYBOARD_KEY_APPS = 0x5D,

        KEYBOARD_KEY_SLEEP = 0x5F,

        KEYBOARD_KEY_NUMPAD0 = 0x60,
        KEYBOARD_KEY_NUMPAD1 = 0x61,
        KEYBOARD_KEY_NUMPAD2 = 0x62,
        KEYBOARD_KEY_NUMPAD3 = 0x63,
        KEYBOARD_KEY_NUMPAD4 = 0x64,
        KEYBOARD_KEY_NUMPAD5 = 0x65,
        KEYBOARD_KEY_NUMPAD6 = 0x66,
        KEYBOARD_KEY_NUMPAD7 = 0x67,
        KEYBOARD_KEY_NUMPAD8 = 0x68,
        KEYBOARD_KEY_NUMPAD9 = 0x69,
        KEYBOARD_KEY_MULTIPLY = 0x6A,
        KEYBOARD_KEY_ADD = 0x6B,
        KEYBOARD_KEY_SEPARATOR = 0x6C,
        KEYBOARD_KEY_SUBTRACT = 0x6D,
        KEYBOARD_KEY_DECIMAL = 0x6E,
        KEYBOARD_KEY_DIVIDE = 0x6F,

        KEYBOARD_KEY_F1 = 0x70,
        KEYBOARD_KEY_F2 = 0x71,
        KEYBOARD_KEY_F3 = 0x72,
        KEYBOARD_KEY_F4 = 0x73,
        KEYBOARD_KEY_F5 = 0x74,
        KEYBOARD_KEY_F6 = 0x75,
        KEYBOARD_KEY_F7 = 0x76,
        KEYBOARD_KEY_F8 = 0x77,
        KEYBOARD_KEY_F9 = 0x78,
        KEYBOARD_KEY_F10 = 0x79,
        KEYBOARD_KEY_F11 = 0x7A,
        KEYBOARD_KEY_F12 = 0x7B,
        KEYBOARD_KEY_F13 = 0x7C,
        KEYBOARD_KEY_F14 = 0x7D,
        KEYBOARD_KEY_F15 = 0x7E,
        KEYBOARD_KEY_F16 = 0x7F,
        KEYBOARD_KEY_F17 = 0x80,
        KEYBOARD_KEY_F18 = 0x81,
        KEYBOARD_KEY_F19 = 0x82,
        KEYBOARD_KEY_F20 = 0x83,
        KEYBOARD_KEY_F21 = 0x84,
        KEYBOARD_KEY_F22 = 0x85,
        KEYBOARD_KEY_F23 = 0x86,
        KEYBOARD_KEY_F24 = 0x87,

        KEYBOARD_KEY_NUMLOCK = 0x90,

        KEYBOARD_KEY_SCROLL = 0x91,

        KEYBOARD_KEY_NUMPAD_EQUAL = 0x92,

        KEYBOARD_KEY_LSHIFT = 0xA0,
        KEYBOARD_KEY_RSHIFT = 0xA1,
        KEYBOARD_KEY_LCONTROL = 0xA2,
        KEYBOARD_KEY_RCONTROL = 0xA3,
        KEYBOARD_KEY_LALT = 0xA4,
        KEYBOARD_KEY_RALT = 0xA5,

        KEYBOARD_KEY_SEMICOLON = 0x3B,

        KEYBOARD_KEY_APOSTROPHE = 0xDE,
        KEYBOARD_KEY_QUOTE = KEYBOARD_KEY_APOSTROPHE,
        KEYBOARD_KEY_EQUAL = 0xBB,
        KEYBOARD_KEY_COMMA = 0xBC,
        KEYBOARD_KEY_MINUS = 0xBD,
        KEYBOARD_KEY_PERIOD = 0xBE,
        KEYBOARD_KEY_SLASH = 0xBF,

        KEYBOARD_KEY_GRAVE = 0xC0,

        KEYBOARD_KEY_LBRACKET = 0xDB,
        KEYBOARD_KEY_PIPE = 0xDC,
        KEYBOARD_KEY_BACKSLASH = KEYBOARD_KEY_PIPE,
        KEYBOARD_KEY_RBRACKET = 0xDD,

        KEYBOARD_KEYS_MAX_KEYS = 0xFF
    };
}
